namespace Trains.NET.Rendering
{
    public enum Colors
    {
        Cyan,
        Green,
        Magenta,
        Purple,
        LightGray,
        Black,
        White,
        Red,
        Blue,
        Gold,
        Gray,
        LegacyDarkRed,
        LegacyLightRed,
        LegacyDarkBlue,
        LegacyLightBlue,
        LegacyDarkGreen,
        LegacyLightGreen,
        LegacyDarkPurple,
        LegacyLightPurple,
        LegacyDarkYellow,
        LegacyLightYellow,
        LegacyNearlyBlack,
        LegacyGray
    }
}
